dist: xenial
language: node_js
before_install:
  - nvm install 11.6.0
  - nvm use 11.6.0
  - npm install npm@6.5.0
  - node -v
  - npm -v
install:
  - npm install
script:
  - npm run build  
after_success:
  - sh .travis-push.sh
